apiVersion: v1
kind: Pod
metadata:
  name: nginx
  label:
    app: nginx
spec:
  containers:
  - name: nginx
    image: graniteviper/landing-page-week-37:65008a8a3983612feaa1f0b4e6b9e1b15e20de12
    ports:
    - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30007
      protocol: TCP
